### ISSUE TITLE
How do I use backend javascipt css?

### ISSUE THREAD

**Issue by lgt** [MatissJanis/oc-frontend-forms-example#1]
Hello,

I like the approach however I have a problem to have the same output as in the backend. Javascript do not work(like select2 ...) even including in my component

```
public function onRun()
    {
        // Build a back-end form with the context of 'frontend'
        $formController = new SupplierController();
        $formController->create('frontend');
        // Append the formController to the page
        $this->page['form'] = $formController;
        // Append the missing style file so that our front-end forms would look
        // just like back-end
        $this->addCss('/modules/backend/assets/css/october.css', 'core');
        $this->addJs('/modules/system/assets/js/framework.extras.js', 'core');
        $this->addJs('/modules/backend/assets/js/backend.js', 'core');
        $this->addJs('/modules/backend/assets/js/october.js', 'core');
    }
```

Is there any chance to have the same result as in the backend

**Comment by MatissJanis** [comment]
Hello, @lgt

OctoberCMS is currently constantly changing so it would be hard to give You a certain answer. I'd suggest that You just look though the JS dependencies (`/modules/backend/assets/js/*`) and read the information at the top of them. Probably You will find Select2 there and information on how to use it.

**Comment by lgt** [comment]
seems to to work with ```$this->addJs('/modules/system/assets/ui/storm-min.js', 'core');```and css

**Comment by MatissJanis** [comment]
Well.. currently it works with that file, but I bet it will change in the near future. Less than a month ago all of the form JS logic was contained in a completely different file. :)
